version: '2'
services:
  kudu-master:
    hostname: 172.25.0.5
    container_name: kudu-master
    image: eskabetxe:kudu
    ports:
      - '18050:8050'
      - '18051:8051'
      - '17050:7050'
      - "17051:7051"
    command: master
    networks:
      mynet:
        ipv4_address: 172.25.0.5

  kudu-server1:
    hostname: 172.25.0.6
    container_name: kudu-server1
    image: eskabetxe:kudu
    ports:
      - '28050:8050'
      - '27050:7050'
    environment:
      - KUDU_MASTER=172.25.0.5
    command: tserver
    networks:
      mynet:
        ipv4_address: 172.25.0.6
    links:
      - kudu-master

  kudu-server2:
    hostname: 172.25.0.7
    container_name: kudu-server2
    image: eskabetxe:kudu
    ports:
      - '38050:8050'
      - '37050:7050'
    environment:
      - KUDU_MASTER=172.25.0.5
    command: tserver
    networks:
      mynet:
        ipv4_address: 172.25.0.7
    links:
      - kudu-master

  kudu-server3:
    hostname: 172.25.0.8
    container_name: kudu-server3
    image: eskabetxe:kudu
    ports:
      - '48050:8050'
      - '47050:7050'
    environment:
      - KUDU_MASTER=172.25.0.5
    command: tserver
    networks:
      mynet:
        ipv4_address: 172.25.0.8
    links:
      - kudu-master


networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          IPRange: 172.25.0.2/24,
          gateway: 172.25.0.1