name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
       java: ['8', '11']
       flink-version: ['1.12.2']
       scala-version: ['2.11', '2.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '${{ matrix.java }}'
        distribution: 'adopt'
        cache: maven 
    - name: Change scala version
      run: ./dev/change-scala-version.sh ${{ matrix.scala-version }}
      shell: bash
    - name: Build with Maven
      run: mvn -q clean verify -Dscala-${{ matrix.scala-version }} -Dflink.version=${{ matrix.flink-version }}
